import time
Numeros = list(range(21))
print(f'=' * 35)
print(Numeros)
print(f'=' * 35)
time.sleep(2)
print(f'=' * 35)
print('Sequência decrescente...')
print(f'=' * 35)
print('Preparando sequência decrescente...')
print(f'=' * 35)
time.sleep(2)
print('Sequência descrescente preparada') 
print(f'=' * 35)
print('Running...')
print(f'=' * 35)
numbers = list(range(20, -1, -1))
print(numbers)
time.sleep(1.5)
print(f'=' * 35)
print('Sequência feita com sucesso!')
print(f'=' * 35)